// Mod pools for the Regex tab builder. "#" marks where numbers sit; texts are
// the EXACT lines as they appear on items - the regex matches real item text,
// so wording is law (incl. the game/poe2db "Otherworldy" spelling). min/max:
// the full roll span across all tiers. bad: player-hostile mods (exclusion
// picker floats them first). prop: waystone tooltip summary lines, pinned
// atop the picker. tabletImplicits: each tablet base's implicit line - a
// 1-pick type filter, folded into the merged tablet pool by the UI.
// Tablet mechanics: the "Precursor Tablet" group is the GENERIC pool (rolls
// on every type incl. Irradiated); other groups are that type's ADDITIVE
// uniques. Compiled from poe2db.tw + poe2wiki.net (never poe2.re - unlicensed).
window.RegexPools = {
  waystone: [
    { text: "Waystone (Tier #)", prop: true, max: 16 },
    { text: "Revives Available: #", hidden: true },
    { text: "Item Level: #", hidden: true },
    { text: "Item Rarity: +#%", prop: true },
    { text: "Pack Size: +#%", prop: true },
    { text: "Monster Rarity: +#%", prop: true },
    { text: "Monster Effectiveness: +#%", prop: true },
    { text: "Waystone Drop Chance: +#%", prop: true },
    { text: "Rare Monsters have # additional Modifiers", min: 1, max: 1, bad: true },
    { text: "#% increased number of Rare Monsters", min: 25, max: 25 },
    { text: "#% increased Waystones found in Area", min: 10, max: 10 },
    { text: "Monsters deal #% of Damage as Extra Fire", min: 5, max: 24, bad: true },
    { text: "Monsters have #% increased Effectiveness", min: 16, max: 16, bad: true },
    { text: "#% more Waystones found in Area", min: 10, max: 25 },
    { text: "Monsters deal #% of Damage as Extra Cold", min: 5, max: 24, bad: true },
    { text: "#% more Rarity of Items found in this Area", min: 10, max: 16 },
    { text: "Monsters deal #% of Damage as Extra Lightning", min: 5, max: 24, bad: true },
    { text: "#% more Pack size", min: 6, max: 10 },
    { text: "#% increased Monster Damage", min: 5, max: 24, bad: true },
    { text: "#% more Magic and Rare Monsters", min: 18, max: 25 },
    { text: "Rare Monsters have #% more chance of Monster Modifiers", min: 18, max: 25, bad: true },
    { text: "Monsters have #% increased Attack,  Cast and Movement Speed", min: 10, max: 15, bad: true },
    { text: "Monsters have #% increased Critical Hit Chance", min: 80, max: 300, bad: true },
    { text: "Monsters have +#% Critical Damage Bonus", min: 11, max: 30, bad: true },
    { text: "#% more Monster Life", min: 10, max: 30, bad: true },
    { text: "+#% Monster Elemental Resistances", min: 20, max: 40, bad: true },
    { text: "Monsters are Armoured", bad: true },
    { text: "Monsters are Evasive", bad: true },
    { text: "Monsters gain #% of maximum Life as Extra maximum Energy Shield", min: 12, max: 25, bad: true },
    { text: "Monsters have #% chance to Poison on Hit", min: 13, max: 40, bad: true },
    { text: "Monsters have #% chance to inflict Bleeding on Hit", min: 5, max: 25, bad: true },
    { text: "Monsters have #% more Effectiveness", min: 13, max: 16, bad: true },
    { text: "Monsters have #% increased Ailment Threshold", min: 30, max: 79, bad: true },
    { text: "Monsters have #% increased Stun Threshold", min: 30, max: 79, bad: true },
    { text: "Monsters Break Armour equal to #% of Physical Damage dealt", min: 15, max: 45, bad: true },
    { text: "Monsters have #% increased Accuracy Rating", min: 10, max: 50, bad: true },
    { text: "Monsters deal #% of Damage as Extra Chaos", min: 5, max: 24, bad: true },
    { text: "Monsters have #% increased Stun Buildup", min: 50, max: 110, bad: true },
    { text: "Monster have #% increased Elemental Ailment Application", min: 60, max: 130, bad: true },
    { text: "Monsters fire # additional Projectiles", min: 2, max: 3, bad: true },
    { text: "Monsters have #% increased Area of Effect", min: 50, max: 50, bad: true },
    { text: "Players are periodically Cursed with Enfeeble", bad: true },
    { text: "Players are periodically Cursed with Temporal Chains", bad: true },
    { text: "Players are periodically Cursed with Elemental Weakness", bad: true },
    { text: "Area has patches of Ignited Ground", bad: true },
    { text: "Area has patches of Chilled Ground", bad: true },
    { text: "Area has patches of Shocked Ground", bad: true },
    { text: "Monster Damage Penetrates #% Elemental Resistances", min: 6, max: 16, bad: true },
    { text: "-#% maximum Player Resistances", min: -10, max: -3, bad: true },
    { text: "Players gain #% reduced Flask Charges", min: 20, max: 35, bad: true },
    { text: "Players have #% less Recovery Rate of Life and Energy Shield", min: 20, max: 40, bad: true },
    { text: "Players have #% less Cooldown Recovery Rate", min: 15, max: 30, bad: true },
    { text: "Monsters take #% reduced Extra Damage from Critical Hits", min: 15, max: 30, bad: true },
    { text: "#% less effect of Curses on Monsters", min: 20, max: 50, bad: true },
    { text: "Abyssal Monsters grant #% increased Experience", min: 50, max: 100 },
    { text: "Area contains # additional Abysses", min: 2, max: 18 },
    { text: "Abysses spawn #% increased Monsters", min: 50, max: 100 },
    { text: "# additional Rare Monsters are spawned from Abysses", min: 3, max: 3 },
    { text: "Area is overrun by the Abyssal" },
    { text: "Abysses lead to an Abyssal Boss" },
    { text: "Area contains # additional Incubator Queens", min: 1, max: 1 },
    { text: "Abyss Pits have #% chance to spawn all Monsters as at least Magic", min: 50, max: 80 },
    { text: "Abyss Cracks have #% chance to spawn all Monsters as at least Magic", min: 40, max: 60 },
    { text: "Abysses lead to an Abyssal Depths" },
    { text: "Abyssal Monsters have increased Difficulty and Reward for each closed Pit" },
    { text: "Abyss Pits in Area always have Rewards" },
    { text: "Natural Rare Monsters in Area have # extra Abyssal Modifiers", min: 1, max: 1, bad: true },
    { text: "Natural Rare Monsters in Area Eat the Souls of slain Monsters in their Presence", bad: true },
    { text: "Players steal the Eaten Souls of Slain Rare Monsters in Area" },
    { text: "Players and their Minions deal no damage for # out of every # seconds", min: 3, max: 3, bad: true },
    { text: "Players have #% less Movement and Skill Speed for each time they've used a Skill Recently", min: 3, max: 3, bad: true },
    { text: "Monsters inflict # Grasping Vines on Hit", min: 1, max: 1, bad: true },
    { text: "Players are Marked for Death for # seconds after killing a Rare or Unique monster", min: 10, max: 10, bad: true },
    { text: "Area has patches of Mana Siphoning Ground", bad: true },
  ],
  tablet: {
    "Precursor Tablet": [
      { text: "Item Level: #", hidden: true },
      { text: "#% increased Rarity of Items found in Map", min: 8, max: 12 },
      { text: "Map contains # additional Summoning Circles", min: 1, max: 1 },
      { text: "#% increased Quantity of Waystones found in Map", min: 30, max: 40 },
      { text: "Map is inhabited by # additional Rogue Exiles", min: 1, max: 1 },
      { text: "Map contains # additional Azmeri Spirits", min: 1, max: 2 },
      { text: "Map contains # additional Essences", min: 1, max: 2 },
      { text: "Monsters have #% increased Effectiveness", min: 10, max: 15, bad: true },
      { text: "Map contains # additional Rare Chests", min: 2, max: 3 },
      { text: "#% increased Experience gain in Map", min: 12, max: 18 },
      { text: "#% increased Gold found in Map", min: 25, max: 35 },
      { text: "Map has #% increased Monster Rarity", min: 15, max: 20 },
      { text: "Map has #% increased number of Rare Monsters", min: 25, max: 35 },
      { text: "Map has #% increased Magic Monsters", min: 30, max: 40 },
      { text: "#% increased Pack Size in Map", min: 5, max: 7 },
      { text: "Map contains # additional Shrines", min: 1, max: 2 },
      { text: "Map contains # additional Strongboxes", min: 1, max: 2 },
      { text: "Map has #% increased chance to contain Rogue Exiles", min: 70, max: 100 },
      { text: "Unique Monsters have # additional Rare Modifiers", min: 1, max: 1, bad: true },
      { text: "Map has # additional random Modifiers", min: 1, max: 2 },
      { text: "Map has #% increased chance to contain a Summoning Circle", min: 70, max: 100 },
      { text: "Map has #% increased chance to contain Azmeri Spirits", min: 70, max: 100 },
      { text: "Map has #% increased chance to contain Essences", min: 70, max: 100 },
      { text: "#% reduced Pack Size in Map", bad: true },
      { text: "Map has #% increased chance to contain Strongboxes", min: 70, max: 100 },
      { text: "Map has #% increased chance to contain Shrines", min: 70, max: 100 },
      { text: "Rare Monsters in Map have a #% Surpassing chance to have an additional Modifier", min: 50, max: 80, bad: true },
    ],
    "Breach Tablet": [
      { text: "Unstable Breaches in Map spawn # additional Rare Monsters when Stabilised", min: 1, max: 3 },
      { text: "Unstable Breaches in Map have #% increased chance to contain Vruun,  Marshal of Xesht", min: 20, max: 50 },
      { text: "#% increased Effectiveness of Rare Breach Monsters in Map", min: 5, max: 20, bad: true },
      { text: "Breaches in Map have #% increased Pack Size", min: 5, max: 15 },
    ],
    "Delirium Tablet": [
      { text: "Delirium Fog in Map spawns #% increased MirrorShards", min: 12, max: 26 },
      { text: "Slaying Rare Monsters in Map pauses the Delirium Mirror Timer for # seconds", min: 3, max: 5 },
      { text: "Delirium Fog in Map spawns #% increased Fracturing Mirrors", min: 15, max: 30 },
      { text: "Delirium Monsters in Map have #% increased Pack Size", min: 15, max: 30 },
      { text: "Delirium Fog in Map applies #% increased Deliriousness to Players", min: 15, max: 30, bad: true },
      { text: "Delirium Fog in Map dissipates #% slower", min: 20, max: 30 },
      { text: "Delirium Fog in Map lasts # additional seconds before dissipating", min: 6, max: 12 },
      { text: "#% increased Stack size of Simulacrum Splinters found in Map", min: 15, max: 30 },
      { text: "Delirium Encounters in Map are #% more likely to spawn Unique Bosses", min: 15, max: 30 },
    ],
    "Expedition Tablet": [
      { text: "#% increased Effect of Expedition Remnants in Map", min: 12, max: 18 },
      { text: "Map contains #% increased number of Runic Monster Markers", min: 15, max: 30 },
      { text: "#% increased number of Rare Expedition Monsters in Map", min: 25, max: 40 },
      { text: "#% increased Quantity of Expedition Logbooks dropped by Runic Monsters in Map", min: 15, max: 30 },
      { text: "#% increased Expedition Explosive Radius in Map", min: 15, max: 30 },
      { text: "Expeditions in Map have +# Remnants", min: 1, max: 2 },
      { text: "#% increased Expedition Explosive Placement Range in Map", min: 15, max: 30 },
      { text: "#% increased quantity of Expedition Artifacts dropped by Monsters in Map", min: 15, max: 30 },
    ],
    "Ritual Tablet": [
      { text: "Ritual Favours in Map have #% increased chance to be Omens", min: 35, max: 70 },
      { text: "Revived Monsters from Ritual Altars in Map have #% increased chance to be Rare", min: 25, max: 40 },
      { text: "Revived Monsters from Ritual Altars in Map have #% increased chance to be Magic", min: 35, max: 70 },
      { text: "Favours Rerolled at Ritual Altars in Map have #% chance to cost no Tribute", min: 3, max: 6 },
      { text: "Ritual Altars in Map allow rerolling Favours # additional times", min: 1, max: 3 },
      { text: "Favours Deferred at Ritual Altars in Map reappear #% sooner", min: 25, max: 40 },
      { text: "Deferring Favours at Ritual Altars in Map costs #% reduced Tribute", min: 20, max: 30 },
      { text: "Rerolling Favours at Ritual Altars in Map costs #% reduced Tribute", min: 20, max: 30 },
      { text: "Monsters Sacrificed at Ritual Altars in Map grant #% increased Tribute", min: 18, max: 30 },
    ],
    "Overseer Tablet": [
      { text: "Map Bosses grant #% increased Experience", min: 40, max: 80 },
      { text: "#% increased Quantity of Waystones dropped by Map Bosses", min: 18, max: 30 },
      { text: "#% increased Rarity of Items dropped by Map Bosses", min: 35, max: 60 },
      { text: "#% increased Quantity of Items dropped by Map Bosses", min: 13, max: 20 },
    ],
    "Abyss Tablet": [
      { text: "Map has #% chance to contain four additional Abysses", min: 20, max: 40 },
      { text: "#% increased chance for Desecrated Currency from Abysses in Map", min: 20, max: 30 },
      { text: "#% increased chance for Abyssal monsters in Map to have Abyssal Modifiers", min: 20, max: 30, bad: true },
      { text: "Abyss Pits in Map are twice as likely to have Rewards" },
      { text: "Map contains # additional Abysses", min: 1, max: 1 },
      { text: "Abysses in Map have #% increased chance to lead to an Abyssal Depths", min: 10, max: 20 },
      { text: "Abyssal Monsters have #% increased Effectiveness for each closed Pit,  up to #%", min: 8, max: 12, bad: true },
      { text: "Abyssal Monsters in Map have increased Difficulty and Reward for each closed Pit" },
      { text: "# additional Rare Monsters are spawned from Abysses in Map", min: 1, max: 2 },
      { text: "Abysses in Map spawn #% increased Monsters", min: 20, max: 30 },
      { text: "Wombgifts have #% chance to drop one Level higher in Map", min: 10, max: 30 },
      { text: "#% increased Quantity of Wombgifts found in Map", min: 30, max: 60 },
      { text: "#% increased Quantity of Hiveblood found in Map", min: 30, max: 60 },
    ],
    "Temple Tablet": [
      { text: "#% increased chance Vaal Beacon Chests are Rare in Map", min: 30, max: 60 },
      { text: "#% chance to add a Vaal Beacon Unique Monster to the Map", min: 10, max: 25 },
      { text: "#% chance to gain an additional Crystal from Vaal Beacons in Map", min: 5, max: 10 },
      { text: "#% increased chance Vaal Beacons summon additional Monsters in Map", min: 25, max: 50 },
      { text: "#% chance for an extra packs of Monsters around Vaal Beacons in Map", min: 30, max: 60 },
      { text: "# extra packs of Monsters around Vaal Beacons in Map", min: 1, max: 1 },
      { text: "#% increased Pack Size for Monsters around Vaal Beacons in Map", min: 10, max: 30 },
    ],
  },
  tabletImplicits: [
    { text: "Adds an Otherworldy Breach to a Map", type: "Breach Tablet" },
    { text: "Adds a Mirror of Delirium to a Map", type: "Delirium Tablet" },
    { text: "Adds a Kalguuran Expedition to a Map", type: "Expedition Tablet" },
    { text: "Adds Ritual Altars to a Map", type: "Ritual Tablet" },
    { text: "Empowers the Map Boss of a Map", type: "Overseer Tablet" },
    { text: "Adds Abysses to a Map", type: "Abyss Tablet" },
    { text: "Adds Vaal Beacons to a Map", type: "Temple Tablet" },
    { text: "Adds Irradiated to a Map", type: "Irradiated Tablet" },
  ],
};
