// GENERATED by dev/build-regex-trade-map.js against GGG's live /api/trade2/data/stats.
// Regex-tab pool line -> trade2 search filter. {id} = stat filter; {id, invert} = the
// pool line is the negative-value rendition of that stat (bound goes on max, negated);
// {filter} = a map_filters range, not a stat. Pool lines missing here are not indexed
// by the trade site at all - the UI surfaces those instead of silently dropping them.
// Rebake when GGG adds stats or the pools change.
window.RegexTradeMap = {
 "Waystone (Tier #)": {
  "filter": "map_tier"
 },
 "Item Rarity: +#%": {
  "filter": "map_iir"
 },
 "Pack Size: +#%": {
  "filter": "map_packsize"
 },
 "Monster Rarity: +#%": {
  "filter": "map_rare_monsters"
 },
 "Monster Effectiveness: +#%": {
  "filter": "map_magic_monsters"
 },
 "Waystone Drop Chance: +#%": {
  "filter": "map_bonus"
 },
 "Monsters deal #% of Damage as Extra Fire": {
  "id": "explicit.stat_92381065"
 },
 "Monsters have #% increased Effectiveness": {
  "id": "explicit.stat_2065500219"
 },
 "Monsters deal #% of Damage as Extra Cold": {
  "id": "explicit.stat_211727"
 },
 "Monsters deal #% of Damage as Extra Lightning": {
  "id": "explicit.stat_512071314"
 },
 "#% increased Monster Damage": {
  "id": "explicit.stat_1890519597"
 },
 "Monsters have #% increased Attack,  Cast and Movement Speed": {
  "id": "explicit.stat_3909654181"
 },
 "Monsters have #% increased Critical Hit Chance": {
  "id": "explicit.stat_2753083623"
 },
 "Monsters have +#% Critical Damage Bonus": {
  "id": "explicit.stat_57326096"
 },
 "#% more Monster Life": {
  "id": "explicit.stat_95249895"
 },
 "+#% Monster Elemental Resistances": {
  "id": "explicit.stat_1054098949"
 },
 "Monsters are Armoured": {
  "id": "explicit.stat_2539290279"
 },
 "Monsters are Evasive": {
  "id": "explicit.stat_2570249991"
 },
 "Monsters gain #% of maximum Life as Extra maximum Energy Shield": {
  "id": "explicit.stat_2887760183"
 },
 "Monsters have #% chance to Poison on Hit": {
  "id": "explicit.stat_95221307"
 },
 "Monsters have #% chance to inflict Bleeding on Hit": {
  "id": "explicit.stat_2506820610"
 },
 "Monsters have #% increased Ailment Threshold": {
  "id": "explicit.stat_1994551050"
 },
 "Monsters have #% increased Stun Threshold": {
  "id": "explicit.stat_4101943684"
 },
 "Monsters Break Armour equal to #% of Physical Damage dealt": {
  "id": "explicit.stat_1879340377"
 },
 "Monsters have #% increased Accuracy Rating": {
  "id": "explicit.stat_1588049749"
 },
 "Monsters deal #% of Damage as Extra Chaos": {
  "id": "explicit.stat_2200661314"
 },
 "Monsters have #% increased Stun Buildup": {
  "id": "explicit.stat_115425161"
 },
 "Monster have #% increased Elemental Ailment Application": {
  "id": "explicit.stat_3877264671"
 },
 "Monsters fire # additional Projectiles": {
  "id": "explicit.stat_1309819744"
 },
 "Monsters have #% increased Area of Effect": {
  "id": "explicit.stat_1708461270"
 },
 "Players are periodically Cursed with Enfeeble": {
  "id": "explicit.stat_2029171424"
 },
 "Players are periodically Cursed with Temporal Chains": {
  "id": "explicit.stat_1629357380"
 },
 "Players are periodically Cursed with Elemental Weakness": {
  "id": "explicit.stat_554690751"
 },
 "Area has patches of Ignited Ground": {
  "id": "explicit.stat_133340941"
 },
 "Area has patches of Chilled Ground": {
  "id": "explicit.stat_349586058"
 },
 "Area has patches of Shocked Ground": {
  "id": "explicit.stat_3477720557"
 },
 "Monster Damage Penetrates #% Elemental Resistances": {
  "id": "explicit.stat_1898978455"
 },
 "-#% maximum Player Resistances": {
  "id": "explicit.stat_3376488707"
 },
 "Players gain #% reduced Flask Charges": {
  "id": "explicit.stat_2549889921"
 },
 "Players have #% less Recovery Rate of Life and Energy Shield": {
  "id": "explicit.stat_4181072906"
 },
 "Players have #% less Cooldown Recovery Rate": {
  "id": "explicit.stat_941368244",
  "invert": true
 },
 "Monsters take #% reduced Extra Damage from Critical Hits": {
  "id": "explicit.stat_337935900"
 },
 "#% less effect of Curses on Monsters": {
  "id": "explicit.stat_3796523155"
 },
 "Abyssal Monsters grant #% increased Experience": {
  "id": "explicit.stat_2975078312"
 },
 "Area contains # additional Abysses": {
  "id": "explicit.stat_3490187949"
 },
 "Abysses spawn #% increased Monsters": {
  "id": "explicit.stat_944630113"
 },
 "# additional Rare Monsters are spawned from Abysses": {
  "id": "explicit.stat_243380454"
 },
 "Area is overrun by the Abyssal": {
  "id": "explicit.stat_2741291867"
 },
 "Abysses lead to an Abyssal Boss": {
  "id": "explicit.stat_2399592398"
 },
 "Area contains # additional Incubator Queens": {
  "id": "explicit.stat_1827854662"
 },
 "Abyss Pits have #% chance to spawn all Monsters as at least Magic": {
  "id": "explicit.stat_4157613372"
 },
 "Abyss Cracks have #% chance to spawn all Monsters as at least Magic": {
  "id": "explicit.stat_1388221282"
 },
 "Abysses lead to an Abyssal Depths": {
  "id": "explicit.stat_2278777540"
 },
 "Abyssal Monsters have increased Difficulty and Reward for each closed Pit": {
  "id": "explicit.stat_360553763"
 },
 "Natural Rare Monsters in Area have # extra Abyssal Modifiers": {
  "id": "explicit.stat_1168851547"
 },
 "Natural Rare Monsters in Area Eat the Souls of slain Monsters in their Presence": {
  "id": "explicit.stat_1266185101"
 },
 "Players steal the Eaten Souls of Slain Rare Monsters in Area": {
  "id": "explicit.stat_1365079333"
 },
 "Players and their Minions deal no damage for # out of every # seconds": {
  "id": "explicit.stat_2408625104"
 },
 "Players have #% less Movement and Skill Speed for each time they've used a Skill Recently": {
  "id": "explicit.stat_4274247770",
  "invert": true
 },
 "Monsters inflict # Grasping Vines on Hit": {
  "id": "explicit.stat_1751584857"
 },
 "Players are Marked for Death for # seconds after killing a Rare or Unique monster": {
  "id": "explicit.stat_436406826"
 },
 "Area has patches of Mana Siphoning Ground": {
  "id": "explicit.stat_3190283174"
 },
 "Adds an Otherworldy Breach to a Map": {
  "id": "implicit.stat_2219129443"
 },
 "Adds a Mirror of Delirium to a Map": {
  "id": "implicit.stat_3879011313"
 },
 "Adds a Kalguuran Expedition to a Map": {
  "id": "implicit.stat_1714888636"
 },
 "Adds Ritual Altars to a Map": {
  "id": "implicit.stat_3166002380"
 },
 "Empowers the Map Boss of a Map": {
  "id": "implicit.stat_3376302538"
 },
 "Adds Abysses to a Map": {
  "id": "implicit.stat_2369421690"
 },
 "Adds Vaal Beacons to a Map": {
  "id": "implicit.stat_3035440454"
 },
 "Adds Irradiated to a Map": {
  "id": "implicit.stat_4041853756"
 },
 "#% increased Rarity of Items found in Map": {
  "id": "explicit.stat_2306002879"
 },
 "Map contains # additional Summoning Circles": {
  "id": "explicit.stat_2839545956"
 },
 "#% increased Quantity of Waystones found in Map": {
  "id": "explicit.stat_2777224821"
 },
 "Map is inhabited by # additional Rogue Exiles": {
  "id": "explicit.stat_3550168289"
 },
 "Map contains # additional Azmeri Spirits": {
  "id": "explicit.stat_358129101"
 },
 "Map contains # additional Essences": {
  "id": "explicit.stat_395808938"
 },
 "Map contains # additional Rare Chests": {
  "id": "explicit.stat_231864447"
 },
 "#% increased Experience gain in Map": {
  "id": "explicit.stat_57434274"
 },
 "#% increased Gold found in Map": {
  "id": "explicit.stat_1276056105"
 },
 "Map has #% increased Monster Rarity": {
  "id": "explicit.stat_4142653832"
 },
 "Map has #% increased number of Rare Monsters": {
  "id": "explicit.stat_3793155082"
 },
 "Map has #% increased Magic Monsters": {
  "id": "explicit.stat_3873704640"
 },
 "#% increased Pack Size in Map": {
  "id": "explicit.stat_2017682521"
 },
 "Map contains # additional Shrines": {
  "id": "explicit.stat_1468737867"
 },
 "Map contains # additional Strongboxes": {
  "id": "explicit.stat_3240183538"
 },
 "Map has #% increased chance to contain Rogue Exiles": {
  "id": "explicit.stat_1352729973"
 },
 "Unique Monsters have # additional Rare Modifiers": {
  "id": "explicit.stat_3371085671"
 },
 "Map has # additional random Modifiers": {
  "id": "explicit.stat_588512487"
 },
 "Map has #% increased chance to contain a Summoning Circle": {
  "id": "explicit.stat_267210597"
 },
 "Map has #% increased chance to contain Azmeri Spirits": {
  "id": "explicit.stat_3815617979"
 },
 "Map has #% increased chance to contain Essences": {
  "id": "explicit.stat_1825943485"
 },
 "#% reduced Pack Size in Map": {
  "id": "explicit.stat_2017682521",
  "invert": true
 },
 "Map has #% increased chance to contain Strongboxes": {
  "id": "explicit.stat_4279535856"
 },
 "Map has #% increased chance to contain Shrines": {
  "id": "explicit.stat_689816330"
 },
 "Rare Monsters in Map have a #% Surpassing chance to have an additional Modifier": {
  "id": "explicit.stat_3732878551"
 },
 "Unstable Breaches in Map spawn # additional Rare Monsters when Stabilised": {
  "id": "explicit.stat_3762913035"
 },
 "Unstable Breaches in Map have #% increased chance to contain Vruun,  Marshal of Xesht": {
  "id": "explicit.stat_2433436306"
 },
 "#% increased Effectiveness of Rare Breach Monsters in Map": {
  "id": "explicit.stat_2895378479"
 },
 "Breaches in Map have #% increased Pack Size": {
  "id": "explicit.stat_1210760818"
 },
 "Delirium Fog in Map spawns #% increased MirrorShards": {
  "id": "explicit.stat_900933517"
 },
 "Slaying Rare Monsters in Map pauses the Delirium Mirror Timer for # seconds": {
  "id": "explicit.stat_2323782229"
 },
 "Delirium Fog in Map spawns #% increased Fracturing Mirrors": {
  "id": "explicit.stat_551040294"
 },
 "Delirium Monsters in Map have #% increased Pack Size": {
  "id": "explicit.stat_3465791711"
 },
 "Delirium Fog in Map applies #% increased Deliriousness to Players": {
  "id": "explicit.stat_1769611692"
 },
 "Delirium Fog in Map dissipates #% slower": {
  "id": "explicit.stat_3350944114",
  "invert": true
 },
 "Delirium Fog in Map lasts # additional seconds before dissipating": {
  "id": "explicit.stat_3226351972"
 },
 "#% increased Stack size of Simulacrum Splinters found in Map": {
  "id": "explicit.stat_3836551197"
 },
 "Delirium Encounters in Map are #% more likely to spawn Unique Bosses": {
  "id": "explicit.stat_3962960008"
 },
 "#% increased Effect of Expedition Remnants in Map": {
  "id": "explicit.stat_3078574625"
 },
 "Map contains #% increased number of Runic Monster Markers": {
  "id": "explicit.stat_1640965354"
 },
 "#% increased number of Rare Expedition Monsters in Map": {
  "id": "explicit.stat_2694800111"
 },
 "#% increased Quantity of Expedition Logbooks dropped by Runic Monsters in Map": {
  "id": "explicit.stat_1083387327"
 },
 "#% increased Expedition Explosive Radius in Map": {
  "id": "explicit.stat_3289828378"
 },
 "Expeditions in Map have +# Remnants": {
  "id": "explicit.stat_3753446846"
 },
 "#% increased Expedition Explosive Placement Range in Map": {
  "id": "explicit.stat_1539368271"
 },
 "#% increased quantity of Expedition Artifacts dropped by Monsters in Map": {
  "id": "explicit.stat_4219583418"
 },
 "#% increased Expedition Explosive Area of Effect in Map": {
  "id": "explicit.stat_3039133122"
 },
 "Expeditions contain # Additional Boss encased in ice in Map": {
  "id": "explicit.stat_1183698646"
 },
 "Expeditions contain # Additional Verisium Sentry in Map": {
  "id": "explicit.stat_1109460697"
 },
 "Verisium Remnants have +#% chance to add an additional Runic Modifier in Map": {
  "id": "explicit.stat_3871299443"
 },
 "Monsters from Verisium Remnants drop #% increased Verisium": {
  "id": "explicit.stat_3520418269"
 },
 "Ritual Favours in Map have #% increased chance to be Omens": {
  "id": "explicit.stat_4219853180"
 },
 "Revived Monsters from Ritual Altars in Map have #% increased chance to be Rare": {
  "id": "explicit.stat_3979184174"
 },
 "Revived Monsters from Ritual Altars in Map have #% increased chance to be Magic": {
  "id": "explicit.stat_1031644647"
 },
 "Favours Rerolled at Ritual Altars in Map have #% chance to cost no Tribute": {
  "id": "explicit.stat_937291386"
 },
 "Ritual Altars in Map allow rerolling Favours # additional times": {
  "id": "explicit.stat_120737942"
 },
 "Favours Deferred at Ritual Altars in Map reappear #% sooner": {
  "id": "explicit.stat_28208665"
 },
 "Deferring Favours at Ritual Altars in Map costs #% reduced Tribute": {
  "id": "explicit.stat_1345835998",
  "invert": true
 },
 "Rerolling Favours at Ritual Altars in Map costs #% reduced Tribute": {
  "id": "explicit.stat_2282052746",
  "invert": true
 },
 "Monsters Sacrificed at Ritual Altars in Map grant #% increased Tribute": {
  "id": "explicit.stat_159726667"
 },
 "Map Bosses grant #% increased Experience": {
  "id": "explicit.stat_3860150265"
 },
 "#% increased Quantity of Waystones dropped by Map Bosses": {
  "id": "explicit.stat_1457896329"
 },
 "#% increased Rarity of Items dropped by Map Bosses": {
  "id": "explicit.stat_4255069232"
 },
 "#% increased Quantity of Items dropped by Map Bosses": {
  "id": "explicit.stat_3119172063"
 },
 "Map has #% chance to contain four additional Abysses": {
  "id": "explicit.stat_2890355696"
 },
 "#% increased chance for Desecrated Currency from Abysses in Map": {
  "id": "explicit.stat_1710200734"
 },
 "#% increased chance for Abyssal monsters in Map to have Abyssal Modifiers": {
  "id": "explicit.stat_2789248444"
 },
 "Abyss Pits in Map are twice as likely to have Rewards": {
  "id": "explicit.stat_4256531808"
 },
 "Map contains # additional Abysses": {
  "id": "explicit.stat_3490187949"
 },
 "Abysses in Map have #% increased chance to lead to an Abyssal Depths": {
  "id": "explicit.stat_2722831300"
 },
 "Abyssal Monsters have #% increased Effectiveness for each closed Pit,  up to #%": {
  "id": "explicit.stat_664606484"
 },
 "Abyssal Monsters in Map have increased Difficulty and Reward for each closed Pit": {
  "id": "explicit.stat_360553763"
 },
 "# additional Rare Monsters are spawned from Abysses in Map": {
  "id": "explicit.stat_243380454"
 },
 "Abysses in Map spawn #% increased Monsters": {
  "id": "explicit.stat_944630113"
 },
 "Wombgifts have #% chance to drop one Level higher in Map": {
  "id": "explicit.stat_2889272422"
 },
 "#% increased Quantity of Wombgifts found in Map": {
  "id": "explicit.stat_472809816"
 },
 "#% increased Quantity of Hiveblood found in Map": {
  "id": "explicit.stat_2778285247"
 },
 "#% increased chance Vaal Beacon Chests are Rare in Map": {
  "id": "explicit.stat_2514439422"
 },
 "#% chance to add a Vaal Beacon Unique Monster to the Map": {
  "id": "explicit.stat_3937291366"
 },
 "#% chance to gain an additional Crystal from Vaal Beacons in Map": {
  "id": "explicit.stat_1940774881"
 },
 "#% increased chance Vaal Beacons summon additional Monsters in Map": {
  "id": "explicit.stat_632698321"
 },
 "#% chance for an extra packs of Monsters around Vaal Beacons in Map": {
  "id": "explicit.stat_1359775981"
 },
 "# extra packs of Monsters around Vaal Beacons in Map": {
  "id": "explicit.stat_3294218801"
 },
 "#% increased Pack Size for Monsters around Vaal Beacons in Map": {
  "id": "explicit.stat_890040946"
 }
};
