'use strict';
// Static slot -> currency map for the PoE2 Essence stash tab (fixed layout).
// Grid: each row = one essence type, each column = a tier (Lesser / Normal /
// Greater / Perfect). Left + right 4-col blocks + middle special/corrupted
// essences. Coords = stack-count number center at 1920x1080 screen capture.
// Types verified against a live tab (Runes of Aldur, 2026-07); tier+position from
// the grid structure (auto). Middle idol/craft slots are not essences (omitted).
(function (root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else (root.Stash = root.Stash || {}).essenceTabMap = api;
})(typeof self !== 'undefined' ? self : this, function () {
  const STATIC_SLOTS = [
    { cx: 60, cy: 203, apiId: 'lesser-essence-of-the-body' },
    { cx: 102, cy: 203, apiId: 'essence-of-the-body' },
    { cx: 160, cy: 203, apiId: 'greater-essence-of-the-body' },
    { cx: 216, cy: 203, apiId: 'perfect-essence-of-the-body' },
    { cx: 60, cy: 260, apiId: 'lesser-essence-of-the-mind' },
    { cx: 102, cy: 260, apiId: 'essence-of-the-mind' },
    { cx: 160, cy: 260, apiId: 'greater-essence-of-the-mind' },
    { cx: 216, cy: 260, apiId: 'perfect-essence-of-the-mind' },
    { cx: 60, cy: 316, apiId: 'lesser-essence-of-enhancement' },
    { cx: 102, cy: 316, apiId: 'essence-of-enhancement' },
    { cx: 160, cy: 316, apiId: 'greater-essence-of-enhancement' },
    { cx: 216, cy: 316, apiId: 'perfect-essence-of-enhancement' },
    { cx: 60, cy: 372, apiId: 'lesser-essence-of-flames' },
    { cx: 102, cy: 372, apiId: 'essence-of-flames' },
    { cx: 160, cy: 372, apiId: 'greater-essence-of-flames' },
    { cx: 216, cy: 372, apiId: 'perfect-essence-of-flames' },
    { cx: 60, cy: 430, apiId: 'lesser-essence-of-insulation' },
    { cx: 102, cy: 430, apiId: 'essence-of-insulation' },
    { cx: 160, cy: 430, apiId: 'greater-essence-of-insulation' },
    { cx: 216, cy: 430, apiId: 'perfect-essence-of-insulation' },
    { cx: 60, cy: 487, apiId: 'lesser-essence-of-ice' },
    { cx: 102, cy: 487, apiId: 'essence-of-ice' },
    { cx: 160, cy: 487, apiId: 'greater-essence-of-ice' },
    { cx: 216, cy: 487, apiId: 'perfect-essence-of-ice' },
    { cx: 60, cy: 543, apiId: 'lesser-essence-of-thawing' },
    { cx: 102, cy: 543, apiId: 'essence-of-thawing' },
    { cx: 160, cy: 543, apiId: 'greater-essence-of-thawing' },
    { cx: 216, cy: 543, apiId: 'perfect-essence-of-thawing' },
    { cx: 60, cy: 599, apiId: 'lesser-essence-of-electricity' },
    { cx: 102, cy: 599, apiId: 'essence-of-electricity' },
    { cx: 160, cy: 599, apiId: 'greater-essence-of-electricity' },
    { cx: 216, cy: 599, apiId: 'perfect-essence-of-electricity' },
    { cx: 60, cy: 657, apiId: 'lesser-essence-of-grounding' },
    { cx: 102, cy: 657, apiId: 'essence-of-grounding' },
    { cx: 160, cy: 657, apiId: 'greater-essence-of-grounding' },
    { cx: 216, cy: 657, apiId: 'perfect-essence-of-grounding' },
    { cx: 60, cy: 713, apiId: 'lesser-essence-of-ruin' },
    { cx: 102, cy: 713, apiId: 'essence-of-ruin' },
    { cx: 160, cy: 713, apiId: 'greater-essence-of-ruin' },
    { cx: 216, cy: 713, apiId: 'perfect-essence-of-ruin' },
    { cx: 398, cy: 202, apiId: 'lesser-essence-of-command' },
    { cx: 440, cy: 202, apiId: 'essence-of-command' },
    { cx: 497, cy: 202, apiId: 'greater-essence-of-command' },
    { cx: 551, cy: 202, apiId: 'perfect-essence-of-command' },
    { cx: 398, cy: 259, apiId: 'lesser-essence-of-abrasion' },
    { cx: 440, cy: 259, apiId: 'essence-of-abrasion' },
    { cx: 497, cy: 259, apiId: 'greater-essence-of-abrasion' },
    { cx: 551, cy: 259, apiId: 'perfect-essence-of-abrasion' },
    { cx: 398, cy: 316, apiId: 'lesser-essence-of-sorcery' },
    { cx: 440, cy: 316, apiId: 'essence-of-sorcery' },
    { cx: 497, cy: 316, apiId: 'greater-essence-of-sorcery' },
    { cx: 551, cy: 316, apiId: 'perfect-essence-of-sorcery' },
    { cx: 398, cy: 373, apiId: 'lesser-essence-of-haste' },
    { cx: 440, cy: 373, apiId: 'essence-of-haste' },
    { cx: 497, cy: 373, apiId: 'greater-essence-of-haste' },
    { cx: 551, cy: 373, apiId: 'perfect-essence-of-haste' },
    { cx: 398, cy: 430, apiId: 'lesser-essence-of-alacrity' },
    { cx: 440, cy: 430, apiId: 'essence-of-alacrity' },
    { cx: 497, cy: 430, apiId: 'greater-essence-of-alacrity' },
    { cx: 551, cy: 430, apiId: 'perfect-essence-of-alacrity' },
    { cx: 398, cy: 487, apiId: 'lesser-essence-of-seeking' },
    { cx: 440, cy: 487, apiId: 'essence-of-seeking' },
    { cx: 497, cy: 487, apiId: 'greater-essence-of-seeking' },
    { cx: 551, cy: 487, apiId: 'perfect-essence-of-seeking' },
    { cx: 398, cy: 543, apiId: 'lesser-essence-of-battle' },
    { cx: 440, cy: 543, apiId: 'essence-of-battle' },
    { cx: 497, cy: 543, apiId: 'greater-essence-of-battle' },
    { cx: 551, cy: 543, apiId: 'perfect-essence-of-battle' },
    { cx: 398, cy: 600, apiId: 'lesser-essence-of-the-infinite' },
    { cx: 440, cy: 600, apiId: 'essence-of-the-infinite' },
    { cx: 497, cy: 600, apiId: 'greater-essence-of-the-infinite' },
    { cx: 551, cy: 600, apiId: 'perfect-essence-of-the-infinite' },
    { cx: 398, cy: 657, apiId: 'lesser-essence-of-opulence' },
    { cx: 440, cy: 657, apiId: 'essence-of-opulence' },
    { cx: 497, cy: 657, apiId: 'greater-essence-of-opulence' },
    { cx: 551, cy: 657, apiId: 'perfect-essence-of-opulence' },
    { cx: 277, cy: 602, apiId: 'essence-of-hysteria' },
    { cx: 330, cy: 602, apiId: 'essence-of-horror' },
    { cx: 277, cy: 656, apiId: 'essence-of-delirium' },
    { cx: 330, cy: 656, apiId: 'essence-of-insanity' },
    { cx: 277, cy: 714, apiId: 'essence-of-the-abyss' },
    { cx: 330, cy: 714, apiId: 'essence-of-the-breach' },
  ];
  return { tab: 'essence', captureSize: { w: 1920, h: 1080 }, STATIC_SLOTS };
});
