// i18n-merge.mjs - fold the per-surface extraction catalogs into the shipped English
// catalog, and split the translator metadata out of it.
//
//   node scripts/i18n-merge.mjs
//
// Input:  dev-docs/i18n/*.json   (one per surface, written by the extraction pass:
//                                 { key: { en, file, line, html, note } })
// Output: renderer/i18n/en.js    (shipped: { key: "English" } only - no metadata bloat
//                                 in the packaged app)
//         dev-docs/i18n/_meta.json  (file/line/html/note per key: what the replacement
//                                 pass needs to find each literal, and what the
//                                 translation pass needs to know about placeholders and
//                                 do-not-translate terms)
//
// It refuses to write on a key collision between surfaces: two surfaces claiming the same
// key would silently overwrite each other's copy.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, "..", "dev-docs", "i18n");
const OUT_JS = path.join(HERE, "..", "renderer", "i18n", "en.js");
const OUT_META = path.join(SRC, "_meta.json");

const files = fs.readdirSync(SRC).filter((f) => f.endsWith(".json") && !f.startsWith("_"));
const en = {};
const meta = {};
const owner = {}; // key -> which surface file claimed it
const collisions = [];
let counts = {};

for (const f of files) {
  const data = JSON.parse(fs.readFileSync(path.join(SRC, f), "utf8"));
  let n = 0;
  for (const [key, v] of Object.entries(data)) {
    if (typeof v !== "object" || v === null || typeof v.en !== "string") {
      throw new Error(`${f}: entry "${key}" has no en string`);
    }
    if (key in en) { collisions.push(`${key}: ${owner[key]} vs ${f}`); continue; }
    owner[key] = f;
    en[key] = v.en;
    meta[key] = { file: v.file || "", line: v.line || 0, html: !!v.html, note: v.note || "" };
    n++;
  }
  counts[f] = n;
}

if (collisions.length) {
  console.error("KEY COLLISIONS - refusing to write:");
  collisions.forEach((c) => console.error("  " + c));
  process.exit(1);
}

const keys = Object.keys(en).sort();
const sortedEn = {};
const sortedMeta = {};
for (const k of keys) { sortedEn[k] = en[k]; sortedMeta[k] = meta[k]; }

fs.mkdirSync(path.dirname(OUT_JS), { recursive: true });
fs.writeFileSync(OUT_JS,
  "'use strict';\n"
  + "// GENERATED by scripts/i18n-merge.mjs - do not hand-edit.\n"
  + "// Source of truth for every user-visible English string. Other languages are\n"
  + "// translations OF this file; a key missing from them falls back here (see i18n.js).\n"
  + "window.I18N_CATALOGS = window.I18N_CATALOGS || {};\n"
  + "window.I18N_CATALOGS.en = " + JSON.stringify(sortedEn, null, 2) + ";\n");
fs.writeFileSync(OUT_META, JSON.stringify(sortedMeta, null, 2) + "\n");

// ---- report ----
const withHtml = keys.filter((k) => sortedMeta[k].html).length;
const withVars = keys.filter((k) => /\{\w+\}/.test(sortedEn[k])).length;
const byText = new Map();
for (const k of keys) {
  const t = sortedEn[k];
  byText.set(t, (byText.get(t) || []).concat(k));
}
const dupes = [...byText.entries()].filter(([, ks]) => ks.length > 1);

console.log("per surface:");
for (const [f, n] of Object.entries(counts)) console.log(`  ${f.padEnd(22)} ${n}`);
console.log(`total keys: ${keys.length}  |  with markup: ${withHtml}  |  with placeholders: ${withVars}`);
console.log(`identical English text under >1 key: ${dupes.length}`);
for (const [text, ks] of dupes.slice(0, 12)) {
  console.log(`  "${text.slice(0, 46)}${text.length > 46 ? "…" : ""}" -> ${ks.join(", ")}`);
}
if (dupes.length > 12) console.log(`  ...and ${dupes.length - 12} more`);
