// i18n-pseudo.mjs - generate the QA pseudo-locale from the English catalog.
//
//   node scripts/i18n-pseudo.mjs
//
// A pseudo-locale is the cheapest way to test localisation before any real translation
// exists. Every string is transformed so that:
//   - accented letters prove the string came from the catalog. Anything still plain
//     English on screen is a HARDCODED string the extraction missed.
//   - it is padded ~35% longer, because German and Russian run long and a button that
//     only fits English is a layout bug we want to see now, not after shipping.
//   - it is bracketed [[ ]], so a string TRUNCATED by CSS is obvious (no closing bracket).
// Placeholders and HTML tags are copied through untouched - if one comes out mangled,
// that is exactly the bug this is meant to catch.
//
// Never shipped to users: the QA entry only appears in the language list when the app
// runs with POE2_OVERLAY_DEBUG set.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const I18N = path.join(HERE, "..", "renderer", "i18n");

const w = {};
new Function("window", fs.readFileSync(path.join(I18N, "en.js"), "utf8"))(w);
const en = w.I18N_CATALOGS.en;

const MAP = { a: "á", e: "é", i: "í", o: "ó", u: "ú", n: "ñ", c: "ć", s: "š", y: "ý", A: "Á", E: "É", I: "Í", O: "Ó", U: "Ú", N: "Ñ", C: "Ć", S: "Š" };
// split on placeholders and tags so we never touch their insides
const KEEP = /(\{\w+\}|<\/?[a-z][^>]*>|&[a-z]+;)/gi;

function pseudo(s) {
  const out = String(s).split(KEEP).map((part, i) => {
    if (i % 2) return part; // captured placeholder / tag / entity
    return part.replace(/[aeiouncsyAEIOUNCS]/g, (ch) => MAP[ch] || ch);
  }).join("");
  // pad to ~135% length, but only for strings with actual words to stretch
  const words = out.replace(KEEP, "").trim();
  const pad = words.length > 3 ? "·".repeat(Math.ceil(words.length * 0.35)) : "";
  return `[[${out}${pad ? " " + pad : ""}]]`;
}

const qa = {};
for (const [k, v] of Object.entries(en)) qa[k] = pseudo(v);

fs.writeFileSync(path.join(I18N, "qa.js"),
  "'use strict';\n"
  + "// GENERATED by scripts/i18n-pseudo.mjs - QA pseudo-locale, never shown to users.\n"
  + "// Accents prove a string came from the catalog; padding proves the layout survives\n"
  + "// longer languages; brackets make CSS truncation visible.\n"
  + "window.I18N_CATALOGS = window.I18N_CATALOGS || {};\n"
  + "window.I18N_CATALOGS.qa = " + JSON.stringify(qa, null, 2) + ";\n");

console.log(`qa.js written: ${Object.keys(qa).length} keys`);
console.log("sample:");
for (const k of ["item.floor.label", "ui.settings.language_label"].filter((k) => qa[k])) {
  console.log(`  ${k}\n    en: ${en[k]}\n    qa: ${qa[k]}`);
}
